# projecct key
sonar.projectKey=131014-989134054

# project name
sonar.projectName=ai-chip-toolchain/aiu-trace-analyzer

# Files / Folders to exclude. Note, this doesn't work unless entered in command-line
sonar.exclusions=""

# SonarQube Host URL
sonar.host.url=https://sonarqube-prod.apps.wdc-sonarqube-prod.core.cirrus.ibm.com
